---
name: first-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    - peer1.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://121.37.132.134:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAPP2HK2vwh3mMRNLKoLAJsAwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjAxMTEwMTA1MzAwWhcNMzAxMTA4MTA1
        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABHWWIsHsMkq6X89NH58gxZi6JmzKLRr8Emlc+wfrwqdfShhdyC+IDjZf
        jtr2YybkAh+/A9W2jADcUPrpl0O5YNejbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgC0IEUKt/VrCpbgecxpn6vcZaKYEMnzWFRSm+5cfX42wwCgYIKoZIzj0E
        AwIDSAAwRQIhAIDjt26zCiROJ5NXBmrVCxFlWCUnKRaQ2nFzL1krFx5RAiAFlckO
        z6uAHfA4q1j+0aLsXmg1F+UW/GVEzvlHBkPYtg==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://121.37.132.134:10051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAPP2HK2vwh3mMRNLKoLAJsAwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjAxMTEwMTA1MzAwWhcNMzAxMTA4MTA1
        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABHWWIsHsMkq6X89NH58gxZi6JmzKLRr8Emlc+wfrwqdfShhdyC+IDjZf
        jtr2YybkAh+/A9W2jADcUPrpl0O5YNejbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgC0IEUKt/VrCpbgecxpn6vcZaKYEMnzWFRSm+5cfX42wwCgYIKoZIzj0E
        AwIDSAAwRQIhAIDjt26zCiROJ5NXBmrVCxFlWCUnKRaQ2nFzL1krFx5RAiAFlckO
        z6uAHfA4q1j+0aLsXmg1F+UW/GVEzvlHBkPYtg==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      hostnameOverride: peer1.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://121.37.132.134:8054
    caName: ca-org2
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICUTCCAfegAwIBAgIQbTFsjaevKTRnAxRFkbogRjAKBggqhkjOPQQDAjBzMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
        b3JnMi5leGFtcGxlLmNvbTAeFw0yMDExMTAxMDUzMDBaFw0zMDExMDgxMDUzMDBa
        MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
        YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
        ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
        8DuOdR0WN9eSQqnTUwW/L3Wn5CxqUAYWWv3wqh/SO1FQfhY1ptyqlMpom2p0Zip0
        hk6P4n22xtu8XcoXORb/jKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
        CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDK
        y+Wzg3eOz5ZaHuBOqNhEjw9vDygA9F1Zv/pqcaZFKTAKBggqhkjOPQQDAgNIADBF
        AiEAiWKS1eoZCVTgZSP0VBVg9XVznIy/Hg+niGqQgnWu7n8CICkbNimaQELBNn5a
        2lctuPmou/r4gxU5EpOEQhpIyQx9
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
