---
name: first-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    - peer1.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://121.37.132.134:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICVzCCAf2gAwIBAgIQNlffhY9JXR/mTcNO3Ch47TAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
        Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yMDExMTAxMDUzMDBaFw0zMDExMDgxMDUz
        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
        VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAED65A551lv2QoGTP67Z6cZMNYGTe36fHruhS0eWf5jjbhi2sYwxsy2zgn
        kVg3rFB48EcTSbqfA/7aaiAr3CVFvKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
        DgQiBCCdw+TDL0tnrQ+p70fNQKTLzbqSvJNctr89VAFUogmW8DAKBggqhkjOPQQD
        AgNIADBFAiEAvmrFKYRbAt1rAqh1BL3qluAYrGDf2fMUcsE1ZNfTT5UCIAIL9sfy
        1NdsUQZsbwyY4gT0U2qmhZHMPKOhSN6Eu5J+
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
  peer1.org1.example.com:
    url: grpcs://121.37.132.134:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICVzCCAf2gAwIBAgIQNlffhY9JXR/mTcNO3Ch47TAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
        Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yMDExMTAxMDUzMDBaFw0zMDExMDgxMDUz
        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
        VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAED65A551lv2QoGTP67Z6cZMNYGTe36fHruhS0eWf5jjbhi2sYwxsy2zgn
        kVg3rFB48EcTSbqfA/7aaiAr3CVFvKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
        DgQiBCCdw+TDL0tnrQ+p70fNQKTLzbqSvJNctr89VAFUogmW8DAKBggqhkjOPQQD
        AgNIADBFAiEAvmrFKYRbAt1rAqh1BL3qluAYrGDf2fMUcsE1ZNfTT5UCIAIL9sfy
        1NdsUQZsbwyY4gT0U2qmhZHMPKOhSN6Eu5J+
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      hostnameOverride: peer1.org1.example.com
  peer0.org2.example.com:
    url: grpcs://121.37.132.134:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAPP2HK2vwh3mMRNLKoLAJsAwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjAxMTEwMTA1MzAwWhcNMzAxMTA4MTA1
        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABHWWIsHsMkq6X89NH58gxZi6JmzKLRr8Emlc+wfrwqdfShhdyC+IDjZf
        jtr2YybkAh+/A9W2jADcUPrpl0O5YNejbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgC0IEUKt/VrCpbgecxpn6vcZaKYEMnzWFRSm+5cfX42wwCgYIKoZIzj0E
        AwIDSAAwRQIhAIDjt26zCiROJ5NXBmrVCxFlWCUnKRaQ2nFzL1krFx5RAiAFlckO
        z6uAHfA4q1j+0aLsXmg1F+UW/GVEzvlHBkPYtg==
        -----END CERTIFICATE-----

    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://121.37.132.134:10051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAPP2HK2vwh3mMRNLKoLAJsAwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjAxMTEwMTA1MzAwWhcNMzAxMTA4MTA1
        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABHWWIsHsMkq6X89NH58gxZi6JmzKLRr8Emlc+wfrwqdfShhdyC+IDjZf
        jtr2YybkAh+/A9W2jADcUPrpl0O5YNejbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgC0IEUKt/VrCpbgecxpn6vcZaKYEMnzWFRSm+5cfX42wwCgYIKoZIzj0E
        AwIDSAAwRQIhAIDjt26zCiROJ5NXBmrVCxFlWCUnKRaQ2nFzL1krFx5RAiAFlckO
        z6uAHfA4q1j+0aLsXmg1F+UW/GVEzvlHBkPYtg==
        -----END CERTIFICATE-----

    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      hostnameOverride: peer1.org2.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://121.37.132.134:7054
    caName: ca-org1
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICUTCCAfigAwIBAgIRAKvU5poolTMuTam7CNSnjWUwCgYIKoZIzj0EAwIwczEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
        Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMTEwMTA1MzAwWhcNMzAxMTA4MTA1MzAw
        WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
        U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
        AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
        BNJ4JFGOZ+J30mfODUPC3lNac5LPeydApGV/XQ4KNVN0kh2CIo3jxPUGutmnR7fo
        JQH9czPZKfHGeXZ4Tebe7ByjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
        BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
        W6QnQw/ozpqPnBVo/Q/y8U3CkAZ0Z9XQOCpV29GOPuwwCgYIKoZIzj0EAwIDRwAw
        RAIgEMwOFnAPf1Z1sXAQAmRKyxySGLcuadxPR0IZREEvC6wCIHco5qFxKx4++Qx6
        PfwU+xfNoDHheObGWkPW+/F+IjXQ
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
  ca.org2.example.com:
    url: https://121.37.132.134:8054
    caName: ca-org2
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICUTCCAfegAwIBAgIQbTFsjaevKTRnAxRFkbogRjAKBggqhkjOPQQDAjBzMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
        b3JnMi5leGFtcGxlLmNvbTAeFw0yMDExMTAxMDUzMDBaFw0zMDExMDgxMDUzMDBa
        MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
        YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
        ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
        8DuOdR0WN9eSQqnTUwW/L3Wn5CxqUAYWWv3wqh/SO1FQfhY1ptyqlMpom2p0Zip0
        hk6P4n22xtu8XcoXORb/jKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
        CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDK
        y+Wzg3eOz5ZaHuBOqNhEjw9vDygA9F1Zv/pqcaZFKTAKBggqhkjOPQQDAgNIADBF
        AiEAiWKS1eoZCVTgZSP0VBVg9XVznIy/Hg+niGqQgnWu7n8CICkbNimaQELBNn5a
        2lctuPmou/r4gxU5EpOEQhpIyQx9
        -----END CERTIFICATE-----

    httpOptions:
      verify: false
